# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(696, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Docs/logo/mini-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.sdStatus = QtWidgets.QLabel(self.centralwidget)
        self.sdStatus.setGeometry(QtCore.QRect(10, 0, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sdStatus.setFont(font)
        self.sdStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.sdStatus.setObjectName("sdStatus")
        self.wifiStatus = QtWidgets.QLabel(self.centralwidget)
        self.wifiStatus.setGeometry(QtCore.QRect(430, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wifiStatus.setFont(font)
        self.wifiStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.wifiStatus.setObjectName("wifiStatus")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setEnabled(False)
        self.uploadButton.setGeometry(QtCore.QRect(0, 230, 411, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setEnabled(False)
        self.checkButton.setGeometry(QtCore.QRect(0, 180, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName("checkButton")
        self.songsButton = QtWidgets.QPushButton(self.centralwidget)
        self.songsButton.setEnabled(False)
        self.songsButton.setGeometry(QtCore.QRect(0, 130, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.songsButton.setFont(font)
        self.songsButton.setObjectName("songsButton")
        self.timeSyncButton = QtWidgets.QPushButton(self.centralwidget)
        self.timeSyncButton.setGeometry(QtCore.QRect(430, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeSyncButton.setFont(font)
        self.timeSyncButton.setObjectName("timeSyncButton")
        self.logButton = QtWidgets.QPushButton(self.centralwidget)
        self.logButton.setEnabled(False)
        self.logButton.setGeometry(QtCore.QRect(0, 30, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logButton.setFont(font)
        self.logButton.setObjectName("logButton")
        self.namesButton = QtWidgets.QPushButton(self.centralwidget)
        self.namesButton.setEnabled(False)
        self.namesButton.setGeometry(QtCore.QRect(0, 80, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.namesButton.setFont(font)
        self.namesButton.setObjectName("namesButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 21))
        self.menubar.setObjectName("menubar")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        self.settings = QtWidgets.QMenu(self.menubar)
        self.settings.setObjectName("settings")
        mainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.settings.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AstriConfigurator"))
        self.sdStatus.setText(_translate("mainWindow", "SD карта не подключена"))
        self.wifiStatus.setText(_translate("mainWindow", "Нет соединения по WIFI"))
        self.uploadButton.setText(_translate("mainWindow", "Загрузить файловую систему на SD карту"))
        self.checkButton.setText(_translate("mainWindow", "Проверить файловую систему"))
        self.songsButton.setText(_translate("mainWindow", "Загрузить мелодии"))
        self.timeSyncButton.setText(_translate("mainWindow", "Синхронизировать время"))
        self.logButton.setText(_translate("mainWindow", "Посмотреть Логи"))
        self.namesButton.setText(_translate("mainWindow", "Настроить имена"))
        self.about.setTitle(_translate("mainWindow", "Справка"))
        self.settings.setTitle(_translate("mainWindow", "Настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
